stages:
  - name: Test--Delete environment
    steps: 
    - runScriptConfig:
        image: iiiorg/rancher-cli:v2.4.6
        shellScript: rancher login ${rancher_url} -t ${rancher_api_token} --skip-verify; rancher kubectl delete deploy ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-db; rancher kubectl delete svc ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-db-service; rancher kubectl delete deploy ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-web; rancher kubectl delete svc ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-web-service
      envFrom:
      - sourceName: rancher-url
        sourceKey: rancher_url
        targetKey: rancher_url
      - sourceName: pipeline-api-key
        sourceKey: API_TOKEN
        targetKey: rancher_api_token
    when:
      branch: [test-src]

  - name: Publish DB image
    steps:
    - publishImageConfig:
        dockerfilePath: ./mariadb/Dockerfile
        buildContext: .
        tag: ${CICD_GIT_REPO_NAME}-db:latest
    when:
      branch:
        exclude: [test-src]

  - name: deploy ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH} db
    steps:
    - applyYamlConfig:
        path: ./mariadb/k8s-deploy/mariadb-deployment.yaml
    - applyYamlConfig:
        path: ./mariadb/k8s-deploy/mariadb-service.yaml

  - name: Publish PHP image
    steps:
    - publishImageConfig:
        dockerfilePath: ./php/Dockerfile
        buildContext: .
        tag: ${CICD_GIT_REPO_NAME}-web:latest
    when:
      branch:
        exclude: [test-src]

  - name: deploy ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH} web
    steps:
    - applyYamlConfig:
        path: ./php/k8s-yaml/php-deployment.yaml
    - applyYamlConfig:
        path: ./php/k8s-yaml/php-service.yaml
