stages:
  - name: Publish DB image
    steps:
    - publishImageConfig:
        dockerfilePath: ./mariadb/Dockerfile
        buildContext: .
        tag: ${CICD_GIT_REPO_NAME}-db:$latest

  - name: deploy ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH} db
    steps:
    - applyYamlConfig:
        path: ./mariadb/k8s-deploy/mariadb-deployment.yaml
    - applyYamlConfig:
        path: ./mariadb/k8s-deploy/mariadb-service.yaml

  - name: Publish PHP image
    steps:
    - publishImageConfig:
        dockerfilePath: ./php/Dockerfile
        buildContext: .
        tag: ${CICD_GIT_REPO_NAME}-web:latest

  - name: deploy ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH} web
    steps:
    - applyYamlConfig:
        path: ./php/k8s-yaml/php-deployment.yaml
    - applyYamlConfig:
        path: ./php/k8s-yaml/php-service.yaml
