stages:
  - name: Publish DB image
    steps:
    - publishImageConfig:
        dockerfilePath: ./mariadb/Dockerfile
        buildContext: .
        tag: ${CICD_GIT_REPO_NAME}-db:${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
