apiVersion: v1
kind: Service
metadata:
  name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-web-service
  labels: 
    app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-web
spec:
  type: NodePort
  selector:
    app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-web
  ports:
    - name: webport
      protocol: TCP
      port: 80
